version: '3'
services:
  db:
    container_name: 
    build: mysql/
    volumes:
      - testing-mysql-data:/var/lib/mysql
      - testing-mysql:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: SecretPassword123
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: WordPressPassword321
    restart: always

  testing-php-fpm:
    build: php-fpm/

  wordpress:
    build: wordpress/
    volumes:
      - testing-wp:/var/www/html
      - testing-mysql:/var/run/mysqld
      - testing-shared:/shared
      - ./data/wordpress/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: localhost:/var/run/mysqld/mysqld.sock
      MYSQL_ROOT_PASSWORD: SecretPassword123
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: WordPressPassword321
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - db
    restart: always

  pma:
    build: phpmyadmin/
    volumes:
      - testing-pma:/var/www/pma
      - testing-shared:/shared
      - testing-mysql:/var/run/mysqld
      - ./data/phpmyadmin/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    restart: always
    links:
      - db:db

  webserver:
    build: nginx/
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - testing-wp:/var/www/html
      - testing-pma:/var/www/pma
      - testing-shared:/shared
    ports:
      - 80:80
    links:
      - wordpress
      - pma
volumes:
  testing-mysql:
  testing-mysql-data:
  testing-wp:
  testing-shared:
  testing-pma:
  
